language:  generic

notifications:
    slack: nozeio:LIFY1Jtkx0FRcLq3u1WliHRZ

matrix:
    include:
        - os:   Linux
          dist: trusty
          env:  SWIFT_SNAPSHOT_NAME="https://swift.org/builds/swift-3.0.1-GM-CANDIDATE/ubuntu1404/swift-3.0.1-GM-CANDIDATE/swift-3.0.1-GM-CANDIDATE-ubuntu14.04.tar.gz"
          sudo: required
        - os:   osx
          osx_image: xcode8

before_install:
    - ./.scripts/before-install.sh

install:
    - ./.scripts/install.sh

script:
    - export PATH="$HOME/usr/bin:$PATH"
    - export SWIFTENV_ROOT="$HOME/.swiftenv"
    - export PATH="${SWIFTENV_ROOT}/bin:${SWIFTENV_ROOT}/shims:$PATH"
    - make all

